### PR TITLE
Add crawler_test.go and some static examples.

### PR DESCRIPTION
**Pull request by chinchila**
**Changes**
- static pages with some links that should and shouldn't be crawled.
- test cases for content and main crawlers.
- setup & teardown database and configuration for testing.

**Issue**
#38

### CODE REVIEW

**Comment by dcwalk** [comment]
Hey @b5 are you able to review when you get the chance?

**Review by b5 — APPROVED** [review]
This is fantastic! Thanks so much @chinchila!

**Comment by b5** [comment]
Thanks so much for this PR @chinchila, I'd like to check with @dcwalk to make sure we're good, and unless there's an issue we'll get this merged. Thanks again!

**Review by dcwalk — APPROVED** [review]

**Comment by dcwalk** [comment]
This is great! Sorry for missing your notification earlier @b5 👍

**Pull request merged**
