### PR TITLE
add usage to README

### PR DESCRIPTION
**Pull request by titaniumbones**
Add Usage and Roadmap sections to READMe.md

- @b5 can you fill in any more tech details?
- @dcwalk any further thoughts?
- @KrzysztofMadejski I think you need more details, so maybe you can improve this PR?

### CODE REVIEW

**Review by b5 — APPROVED** [review]
thanks @titaniumbones!

**Review by dcwalk — APPROVED** [review]
I think this is good, I just updated the docker instructions to reflect the `webapp` repo. @b5 can you review and merge in if acceptable?

**Review by KrzysztofMadejski — APPROVED** [review]
Seems like it have all the relevant information!

**Comment by b5** [comment]
well then LGTM!

**Pull request merged**
